# https://dev.azure.com/NabuCasa/OpenSource

trigger:
  branches:
    include:
    - master
    - dev
  tags:
    include:
    - '*'
    exclude:
    - untagged*
pr:
- dev

variables:
  - group: twine


jobs:

- job: "Tox"
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - script: pip install tox
    displayName: 'Install Tox'
  - script: tox
    displayName: 'Run Tox'


- job: 'Black'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7'
    inputs:
      versionSpec: '3.7'
  - script: pip install black
    displayName: 'Install black'
  - script: |
      black --target-version py36 --check hass_nabucasa tests
    displayName: 'Run Black'


- job: 'Release'
  condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags'), succeeded('Tox'), succeeded('Black'))
  dependsOn:
  - 'Tox'
  - 'Black'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7'
    inputs:
      versionSpec: '3.7'
  - script: |
      setup_version="$(python setup.py -V)"
      branch_version="$(Build.SourceBranchName)"

      if [ "${setup_version}" != "${branch_version}" ]; then
        echo "Version of tag ${branch_version} don't match with ${setup_version}!"
        exit 1
      fi
    displayName: 'Check version of branch/tag'
  - script: pip install twine wheel
    displayName: 'Install twine'
  - script: python setup.py sdist bdist_wheel
    displayName: 'Build package'
  - script: |
      export TWINE_USERNAME="$(twineUser)"
      export TWINE_PASSWORD="$(twinePassword)"

      twine upload dist/*
    displayName: 'Upload pypi'
